# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'
platform :ios, '8.0'
use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

target 'Tags' do

end

pod 'PebbleKit'
pod 'SSKeychain'
pod "RATreeView", "~> 0.9.2"
pod 'SWTableViewCell', '~> 0.3.7'
pod 'Underscore.m'
pod 'RMMapper'
pod 'NSDate-Escort'
pod 'Charts'
pod 'SSZipArchive'
